### ISSUE TITLE
Maybe should add some css code to avoid big images out of bound?

### ISSUE THREAD

**Issue by visig9** [vladris/tinkerer#14]
Like this...

``` css
article > img, article > figure > img {
    max-width: 100%;
}
```

Reference:
http://www.w3schools.com/cssref/pr_dim_max-width.asp
